Reorganize logs and build directories

diff --git a/targets/SNAP/action/hw/Makefile b/targets/SNAP/action/hw/Makefile
--- a/targets/SNAP/action/hw/Makefile
+++ b/targets/SNAP/action/hw/Makefile
@@ -3,11 +3,13 @@ $(info You have specified a wrong $$SNAP_ROOT.)
 $(error Please make sure that $$SNAP_ROOT is set up correctly.)
 endif
 
+export ACTION_BUILDROOT=$(IMAGE_BUILD_DIR)/$(SNAP_TARGET)/action
+
 vhd_srcs=$(wildcard *.vhd_source)
-vhd_files=$(vhd_srcs:.vhd_source=.vhd)
+vhd_targets=$(addprefix $(ACTION_BUILDROOT)/,$(vhd_srcs))
+vhd_files=$(vhd_targets:.vhd_source=.vhd)
 
 ACTION_ROOT ?= $(PWD)/..
-LOGS_DIR    ?= $(PWD)/../logs
 CONFIG_FILE  = $(SNAP_ROOT)/.snap_config
 
 hls_components  = $(shell find hls/ -maxdepth 1 -type d -name 'hls_*')
@@ -38,20 +40,29 @@ endif
 
 all: vhd_files block_design
 
+$(LOGS_DIR):
+	@mkdir -p $(LOGS_DIR)
+
 block_design: hls nvme_arbiter image_info $(LOGS_DIR)
 	@echo "                        Generating Block Design"
-	@make -C $(ACTION_ROOT)/ip/block_design ip
+	@make -C $(ACTION_ROOT)/ip/block_design ip > $(LOGS_DIR)/$(@F)_make.log; viv_ret=$$?; \
+	if [ $${viv_ret} -ne 0 ]; then \
+		echo "                        Error: please look into $(LOGS_DIR)/$(@F)_make.log"; exit -1; \
+	fi
 
 image_info: $(IMAGE_TARGET) $(LOGS_DIR)
 	@echo "                        Generating Image Info"
-	@make -C $(ACTION_ROOT)/ip/image_info ip
+	@make -C $(ACTION_ROOT)/ip/image_info ip > $(LOGS_DIR)/$(@F)_make.log; viv_ret=$$?; \
+	if [ $${viv_ret} -ne 0 ]; then \
+		echo "                        Error: please look into $(LOGS_DIR)/$(@F)_make.log"; exit -1; \
+	fi
 
 nvme_arbiter: $(LOGS_DIR)
 	@echo "                        Generating NVMe Arbiter"
-	@make -C $(ACTION_ROOT)/ip/nvme_arbiter ip
-
-$(LOGS_DIR):
-	@mkdir -p $(LOGS_DIR)
+	@make -C $(ACTION_ROOT)/ip/nvme_arbiter ip > $(LOGS_DIR)/$(@F)_make.log; viv_ret=$$?; \
+	if [ $${viv_ret} -ne 0 ]; then \
+		echo "                        Error: please look into $(LOGS_DIR)/$(@F)_make.log"; exit -1; \
+	fi
 
 hls: $(hls_components)
 
@@ -65,7 +76,10 @@ $(hls_components): $(LOGS_DIR)
 
 vhd_files: $(vhd_files)
 
-$(vhd_files): $(vhd_srcs)
+$(ACTION_BUILDROOT):
+	@mkdir -p $(ACTION_BUILDROOT)
+
+$(vhd_files): $(vhd_srcs) $(ACTION_BUILDROOT)
 	@echo "                        Generating $@"
 	@grep -v $(DDRI_FILTER) $< | grep -v $(NVME_FILTER) > $@
 
